// Define categories and their associated events
export const eventCategories = {
  metadata: [
    "thread_name",
    "process_name",
    "process_labels",
    "thread_sort_index",
    "process_sort_index",
    "v8.isolate",
    "v8.gc",
    "benchmark_metadata",
    "trace_config",
    "clock_sync",
    "stackFrames",
  ],
  taskExecution: [
    "RunTask",
    "FireAnimationFrame",
    "TimerFire",
    "TimerInstall",
    "TimerRemove",
    "EventDispatch",
    "FunctionCall",
    "JSAsyncEvent",
    "V8.Execute",
  ],
  javascript: [
    "EvaluateScript",
    "CompileScript",
    "V8.Compile",
    "V8.Parse",
    "V8.OptimizeCode",
    "V8.DeoptimizeCode",
    "V8.RegExpCompile",
  ],
  rendering: [
    "Layout",
    "Paint",
    "UpdateLayerTree",
    "ActivateLayerTree",
    "CompositeLayers",
    "DrawFrame",
    "GPUTask",
    "GPUBeginFrame",
    "GPUProcessCommandBuffer::ScheduleTask",
    "Commit",
  ],
  networking: [
    "ResourceSendRequest",
    "ResourceReceiveResponse",
    "ResourceReceiveData",
    "ResourceFinish",
    "WebSocketCreate",
    "WebSocketHandshakeStart",
    "WebSocketHandshakeResponseReceived",
    "WebSocketSendFrame",
    "WebSocketReceiveFrame",
    "HttpRequest::WillSendRequest",
  ],
  navigation: [
    "NavigationStart",
    "CommitLoad",
    "FirstContentfulPaint",
    "LargestContentfulPaint::Candidate",
    "ParseHTML",
    "DidCommitProvisionalLoadForFrame",
  ],
  memory: ["Memory.Measure", "V8.GCCompactor", "V8.GCMarking", "V8.GCSweeping"],
  input: ["TouchEvent", "MouseMove", "KeyDown", "KeyUp"],
  browser: ["CrBrowserMain", "Compositor", "Swapper", "CrRendererMain"],
  other: ["Program", "decodeImage", "encodeImage", "Media", "Extension"],
};
